### ISSUE TITLE
Way to delete original files

### ISSUE THREAD

**Issue by AMerkuri** [4awpawz/buster#4]
I would be really grateful for option to delete original files and backup files `index.buster-copy.html`.

**Comment by jeffschwartz** [comment]
@AMerkuri I'm not sure I understand your request. Can you please provide more information or perhaps a use-case?

**Comment by jeffschwartz** [comment]
When running "restore" what files do you want to delete that aren't being deleted? Can you share your configuration here?

**Comment by jeffschwartz** [comment]
The restoration of backup files is partially broken in v0.1.6. v0.2.0 includes a fix for that and should be public today or tomorrow.

**Comment by AMerkuri** [comment]
Currently I am using two tasks for that:
"cache:bust": "buster bust",
"cache:delete": "del-cli dist/index.buster-copy.html dist/css/main.min.css dist/js/app.bundle.min.js".

I would like to delete original files and keep only new files generated by buster for deployment.

**Comment by jeffschwartz** [comment]
@AMerkuri v0.2.0 is now public on npm. Please read the docs about safe mode prior to using it.

**Comment by jeffschwartz** [comment]
As "safe mode" addresses your use-case I am closing out this issue.

**Comment by jeffschwartz** [comment]
@AMerkuri that's odd because it looks like it didn't recognize the "-s" option. Are you using version (v0.2.0)? When you run `$ buster -V` in the terminal it should output `0.2.0`.

**Comment by DavidOliver** [comment]
I was having this issue and it seems to be because I was trying to use the `-s` flag in combination with `.buster.json` config. I removed the flag and added `"safeMode": true,` to the options in `.buster.json` and the original files are now being removed.

The readme does explain config resolution, but I was thrown off by the documentation only mentioning safe mode's CLI flag.

Thanks very much for making buster available, @jeffschwartz. Seems like a great way of busting without having to use, e.g., Webpack when you don't otherwise need to.
